### ISSUE TITLE
Starting up is still complicated!

### ISSUE THREAD

**Issue by hansgru** [onyx-platform/onyx-starter#3]
Starting up with Onyx still seems to be quite complicated and confusing.

IMO a default example:
- should use RDBMS (SQL) : this is what most business still require
- should not use clustering: it makes everything just more complicated, and for "not big data" it's not even needed.
- should include some sort of monitoring, to be able to know what's happening.

Other questions:
- how to structure files? One would expect the config/catalog to be in some sort of separate config/EDN file.
- is there a "lein template" for this "starter" ?

thnx

**Comment by MichaelDrogalis** [comment]
Still a little alpha, but have at it: https://github.com/onyx-platform/onyx-template

**Comment by MichaelDrogalis** [comment]
Gonna close since I presume this will help a lot. Feel free to open issues on `onyx-template` repo if you'd like to make changes there.
