### ISSUE TITLE
Error: You don't have enough free space in /var/cache/apt/archives/.

### ISSUE THREAD

**Issue by gigafone** [onyx-platform/onyx-starter#5]
When I run `source script/build.sh`, I get this:

```
Compiling onyxexample.launcher.aeron-media-driver
Compiling onyxexample.launcher.launch-prod-peers
Compiling onyxexample.launcher.aeron-media-driver
Compiling onyxexample.launcher.launch-prod-peers
Created /Users/me/dev/stuff/onyxexample/target/onyxexample-0.1.0-SNAPSHOT.jar
Created /Users/me/dev/stuff/onyxexample/target/onyxexample-0.1.0-SNAPSHOT-standalone.jar
Sending build context to Docker daemon  53.5 MB
Step 1 : FROM phusion/baseimage:0.9.17
 ---> ea7f812691cd
Step 2 : MAINTAINER Michael Drogalis <mjd3089@rit.edu>
 ---> Using cache
 ---> d91238505791
Step 3 : RUN add-apt-repository -y ppa:webupd8team/java
 ---> Using cache
 ---> 97be8f28ec5c
Step 4 : RUN apt-get install -y software-properties-common
 ---> Using cache
 ---> 91a73d77305d
Step 5 : RUN apt-get update
 ---> Using cache
 ---> a3eb34aa4c7f
Step 6 : RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
 ---> Using cache
 ---> aa078d1f8dd1
Step 7 : RUN apt-get install -y oracle-java8-installer
 ---> Running in 9df9d74b9c1c
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  binutils gsfonts gsfonts-x11 java-common libfontenc1 libfreetype6 libxfont1
  wget x11-common xfonts-encodings xfonts-utils
Suggested packages:
  binutils-doc default-jre equivs binfmt-support visualvm ttf-baekmuk
  ttf-unfonts ttf-unfonts-core ttf-kochi-gothic ttf-sazanami-gothic
  ttf-kochi-mincho ttf-sazanami-mincho ttf-arphic-uming firefox firefox-2
  iceweasel mozilla-firefox iceape-browser mozilla-browser epiphany-gecko
  epiphany-webkit epiphany-browser galeon midbrowser moblin-web-browser
  xulrunner xulrunner-1.9 konqueror chromium-browser midori google-chrome
The following NEW packages will be installed:
  binutils gsfonts gsfonts-x11 java-common libfontenc1 libfreetype6 libxfont1
  oracle-java8-installer wget x11-common xfonts-encodings xfonts-utils
0 upgraded, 12 newly installed, 0 to remove and 49 not upgraded.
Need to get 7002 kB of archives.
After this operation, 20.6 MB of additional disk space will be used.
E: You don't have enough free space in /var/cache/apt/archives/.
The command '/bin/sh -c apt-get install -y oracle-java8-installer' returned a non-zero code: 100
```

**Comment by gardnervickers** [comment]
This is an issue with how apt-get caching is configured on the base image. I added apt-get clean to the Dockerfile, this should save some space in the base image. You may need to delete your cached base images for this to take effect.

![](https://dl.dropboxusercontent.com/s/jdnlt99s40u8ktx/7D0AA662-87EF-4ECB-AA21-388BC0F0F03A-17405-000039A1CDDC13D4.gif?dl=0)

**Comment by acron0** [comment]
I'm seeing this problem still exist today.

**Comment by lbradstreet** [comment]
After discussing with acron0 on slack, this was a separate issue where Aeron needed more shm space.

**Comment by acron0** [comment]
@lbradstreet Actually, I never solved this issue, but stopped using this Dockerfile in favour of the onyx-template version, which didn't exhibit the same behaviour.

**Comment by lbradstreet** [comment]
OK, I think it was a separate problem still - unless you were hitting an apt error, not the error on starting peer-group issue.

**Comment by acron0** [comment]
I was getting the `The command '/bin/sh -c apt-get install -y oracle-java8-installer' returned a non-zero code: 100` error, yeah. But it was intermittent.

**Comment by lbradstreet** [comment]
OK, it was the same issue then. Thank you.

**Comment by speedplane** [comment]
I'm still seeing this intermittently.

**Comment by speedplane** [comment]
The issue was because Docker had a large number of unused containers that had to be cleared, the following fixed it:

```
docker rmi $(docker images -q)
docker rm -v $(docker ps -qa)
```

**Comment by stuarthu** [comment]
`docker container prune` can fix it as well

**Comment by tublitzed** [comment]
`docker image prune` did it for me.

`Total reclaimed space: 51.51GB` 😱

**Comment by robinfhu** [comment]
Thank you @speedplane .  Your solution fixed this exact issue for me.

**Comment by UdaniWijesinghe** [comment]
Thanks @tublitzed. It helped to fix my issue.

**Comment by indhio** [comment]
@stuarthu did it to me too. 

Total reclaimed space: 6.109GB

**Comment by saumpsh** [comment]
The following command worked for me :
```
$ docker system prune
```
Reference: [unix.stackexchange](https://unix.stackexchange.com/a/616283/444282)

**Comment by Flyingpig233** [comment]
> The following command worked for me :
> 
> ```
> $ docker system prune
> ```
> 
> Reference: [unix.stackexchange](https://unix.stackexchange.com/a/616283/444282)

solved my issue!!!! tysm
