### ISSUE TITLE
Walkthrough does not match code examples

### ISSUE THREAD

**Issue by mushketyk** [onyx-platform/onyx-starter#8]
In the "in" section in the description of the catalog, walk-through mentions "consumption" parameter that is not present in the code example above. Also description of "max-peers" parameter is missing.

**Comment by MichaelDrogalis** [comment]
Thanks for the report @mushketyk! The walkthrough is pretty old, and I admittedly forget that it's there sometimes. I'll update it as soon as I can.

**Comment by MichaelDrogalis** [comment]
Do either @bridgethillyer or @gardnervickers have spare time to pick this one up? If not I can take it on next week, just let me know.
